name: main
on: [ push ]
env:
  GATSBY_SITE_URL: https://docs.meli.sh
  GATSBY_GITHUB_DOCS_URL: "https://github:com/getmeli/docs/tree/master/src/data"
  GATSBY_ALGOLIA_APP_ID: "CX0A5WLCWE"
  GATSBY_ALGOLIA_INDEX_NAME: "docs-prod"
  GATSBY_ALGOLIA_SEARCH_ONLY_KEY: "16c14bda60a1b9edfce612eb56139706"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: "install dependencies"
        run: npm ci
      - name: "build"
        run: npm run build
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
#      - name: "publish"
#        # TODO add MELI_TOKEN
#        run: npx @getmeli/cli upload -t $MELI_TOKEN -p $MELI_PROJECT ./build
#        env:
#          MELI_PROJECT: "xxxxxxx"
