name: main
on: [ push ]
env:
  GATSBY_SITE_URL: https://docs.meli.sh
  GATSBY_GITHUB_DOCS_URL: "https://github:com/getmeli/docs/tree/master/src/data"
  GATSBY_ALGOLIA_APP_ID: "CX0A5WLCWE"
  GATSBY_ALGOLIA_INDEX_NAME: "docs-prod"
  GATSBY_ALGOLIA_SEARCH_ONLY_KEY: "16c14bda60a1b9edfce612eb56139706"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: "install dependencies"
        run: npm ci
      - name: "build"
        run: npm run build
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      - name: "publish"
        run: |
          npx @meli/cli upload \
              --url https://cloud.meli.sh \
              --site ccb81d07-e898-4214-9adb-00399dff015d \
              --token $MELI_TOKEN \
              <path>
        env:
          MELI_TOKEN: ${{ secrets.MELI_TOKEN }}
